apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: s6eebvuua-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/s6eebvuua-dotnet-basic-gitops